apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleproject
  labels:
    app: sampleproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleproject
  template:
    metadata:
      labels:
        app: sampleproject
    spec:
      containers:
        - name: sampleproject
          image: gcr.io/nodejs-k8s-350419/github.com/mahirazeem/ctseassignment
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
